apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-front
  template:
    metadata:
      labels:
        app: app-front
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9999"
    spec:
      containers:
        - name: app-front
          image: pretoriano88/appf:1.0
          ports:
            - containerPort: 5000
              name: apppy
            - containerPort: 9999
              name: appmetrics
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DATABASE_URL
            - name: MEMCACHED_HOST
              valueFrom:
                configMapKeyRef:
                  name: memcached-config
                  key: MEMCACHED_HOST
            - name: MEMCACHED_PORT
              valueFrom:
                configMapKeyRef:
                  name: memcached-config
                  key: MEMCACHED_PORT
            
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.monitoring:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"



---
apiVersion: v1
kind: Service
metadata:
  name: app-front
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
spec:
  type: LoadBalancer
  selector:
    app: app-front
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: apppy
    - name: metrics
      protocol: TCP
      port: 9999
      targetPort: appmetrics

